AdvancedReservationSystem/config/routes.rb
Rails.application.routes.draw do
  resources :extra_reservations
  resources :events
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :customer_reservations
  resources :customers
  resources :reservations
  resources :flights
  resources :airlines
  resources :airports
  resources :reservation_steps
  scope "extra_reservations/:extra_reservation_id" do
    resources :extra_steps
  end
  
  
  match "extra_steps/taxi", to: "extra_steps#taxi", via: "post"
  
  
  get 'admin' =>'admin'

  

  root 'flights#index'

end

AdvancedReservationSystem/app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :flight
  belongs_to :user
	has_many :customer_reservations
	has_many :customers, through: :customer_reservations

	validates :flight_id, presence: true

	accepts_nested_attributes_for :customers
  
end

AdvancedReservationSystem/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_admin_user!, :except => [:index]
  before_action :authenticate_user!
  

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.where(:user_id => current_user)   
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])
  end

  # GET /reservations/new
  def new
    @flight = Flight.find(params[:flight_id])
    @reservation = Reservation.new
    params[:customers].to_i.times { @reservation.customers.build }
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id if current_user
    if @reservation.save
      @reservation.customers.each do |p|
        CustomerMailer.thank_you(p).deliver
      end
      redirect_to new_extra_reservation_path # (@extra_reservation)
      flash[:success] = "Your Flight has been successfully Reserved."
    else
      @flight = Flight.find(params[:flight_id])
      render 'new'
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to new_flight_path, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:flight_id, customers_attributes: [:id, :name, :email, :address])
    end
end

AdvancedReservationSystem/app/helpers/reservations_helper.rb
module ReservationsHelper
end

AdvancedReservationSystem/app/views/reservations/_editor.html.erb
<div class="row customer_details">
	<div class="col-md-8 col-md-offset-2">

		<div class="row">
			<h3>Reservation Cannot be Changed</h3>
			<p>Alternatively, You can Cancle and Book</p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2 well booking">		  
			  
			<table class="table">
				<thead>
					<tr>
						<th>Reservation Number:</th>
						<th>Departing Airport</th>
						<th>Departing Airport Code</th>
						<th>Arrival Airport</th>
						<th>Arrival Airport Code</th>
						<th>Departure Date</th>
						<th>Departure Time</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td><%= @reservation.id %></td>
						<td><%= @reservation.flight.departure_airport.name %></td>
						<td><%= @reservation.flight.departure_airport.code %></td>
						<td><%= @reservation.flight.arrival_airport.name %></td>
						<td><%= @reservation.flight.arrival_airport.code %></td>
						<td><%= @reservation.flight.departure_date.strftime("%d/%m/%Y") %></td>
						<td><%= @reservation.flight.departure_date.strftime("%H:%M") %></td>
					</tr>
				</tbody>
			</table>

			<h3>Travellers details</h3>
			<table class="table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Address</th>
					</tr>
				</thead>

				<tbody>
					<% @reservation.customers.each do |c| %>
					<tr>
						<td><%= c.name %></td>
						<td><%= c.email %></td>
						<td><%= c.address %></td>
					</tr>
					<% end %>
				</tbody>
			
			</table>	
					
			<%= link_to 'Show', @reservation, class: 'btn btn-table-action btn-info' %> |
			<%= link_to 'Back', reservations_path, class: 'btn btn-table-action btn-success' %>

					  
		</div>
	</div>

AdvancedReservationSystem/app/views/reservations/_form.html.erb
<div class="row customer_details">
	<div class="col-md-6 col-md-offset-3">

		<div class="row">
			<h2>Traveller(s) Details</h2>
			<p>Please provide Traveller(s) details for flight:</p>

			<div class=" col-md-12 well flight-details">
				<div class"panel-body">
					<table class="table">
						<thead>
							<tr>
								<th>Flight Number:</th>
								<th>Departing Airport</th>
								<th>Arrival Airport</th>
								<th>Departure Date</th>
								<th>Departure Time</th>
							</tr>
						</thead>

						<tbody>
							<tr>
								<td><%= @flight.id %></td>
								<td><%= @flight.departure_airport.name %></td>
								<td><%= @flight.arrival_airport.name %></td>
								<td><%= @flight.departure_date.strftime("%d/%m/%Y") %></td>
								<td><%= @flight.departure_date.strftime("%H:%M") %></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<%= form_for @reservation, :html => { :class => "form-horizontal" } do |flight|  %>
		<% if @reservation.errors.any? %>
		<div id="error_explanation">

			<h2>
				<%= pluralize(@reservation.errors.count, "error") %> 
			</h2>
 
			<ul>
				<% @reservation.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		
		<% customer_num = 1 %>

		<%= flight.fields_for :customers do |customer| %>
		<div class="row">
			<div class="col-md-12 well customer-box">
				<h3>Traveller <%= customer_num %></h3>
				<% customer_num += 1 %>

				<div class="form-group">
					<%= customer.label :name, "Name:", class: "control-label col-md-2"%>
					<div class="col-md-9">
						<%= customer.text_field :name, class: "form-control"%>
					</div>
				</div>

				<div class="form-group">
					<%= customer.label :email, "Email:", class: "control-label col-md-2" %>
					<div class="col-md-9">
						<%= customer.text_field :email, class: "form-control" %>
					</div>
				</div>
			  
				<div class="form-group">
					<%= customer.label :address, "Address:", class: "control-label col-md-2" %>
					<div class="col-md-9">
						<%= customer.text_field :address, class: "form-control" %>
					</div>
				</div>

			</div>
		</div>
				
		<% end %>
		
				 
		<%= hidden_field_tag(:hotel, params[:hotel]) %>
		<%= hidden_field_tag(:customers, params[:customers]) %>
		<%= flight.hidden_field :flight_id, value: params[:flight_id] %>
		<%= hidden_field_tag(:flight_id, params[:flight_id]) %>
  
		<%= flight.submit "Book Flight", class: "btn btn-success btn-lg col-md-4 col-md-offset-4" %>
		<% end %>
				
	</div>
</div>

AdvancedReservationSystem/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'editor' %>

AdvancedReservationSystem/app/views/reservations/index.html.erb
<div class="col-md-10 col-md-offset-1">

	<h1>Your Flight Reservations</h1>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>Customer No</th>
				<th>Flight</th>
				<th colspan="2"></th>
			</tr>
		</thead>

		<tbody>
			<% @reservations.each do |reservation| %>
			<tr>
				<td><%= reservation.user_id %></td>
				<td><%= reservation.flight_id %></td>
				<td><%= link_to 'Show', reservation, class: 'btn btn-table-action btn-success' %></td>
				<td><%= link_to 'Edit', edit_reservation_path(reservation), class: 'btn btn-table-action btn-info' %></td>
			</tr>
			<% end %>
		</tbody>
				
	</table>

	<br>
	
		<%= link_to 'Make New Reservation', flights_path %>

	<br><br><br><br><br>

</div>

AdvancedReservationSystem/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

AdvancedReservationSystem/app/views/reservations/show.html.erb
<h1>Your Flight has Been Reserved!</h1>
<div class="row">
	<div class="col-md-8 col-md-offset-2 well booking">

		<h3>Flight Details</h3>

		<p>
			<strong>Your Customer ID:</strong>
			<%= @reservation.user_id %>
		</p>
		<p>
			<strong>Reservation ID:</strong>
			<%= @reservation.id %>
		</p>
		
		<table class="table">
			<thead>
				<tr>
					<th>Booking Number:</th>
					<th>Departing Airport</th>
					<th>Departing Airport Code</th>
					<th>Arrival Airport</th>
					<th>Arrival Airport Code</th>
					<th>Departure Date</th>
					<th>Departure Time</th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td><%= @reservation.id %></td>
					<td><%= @reservation.flight.departure_airport.name %></td>
					<td><%= @reservation.flight.departure_airport.code %></td>
					<td><%= @reservation.flight.arrival_airport.name %></td>
					<td><%= @reservation.flight.arrival_airport.code %></td>
					<td><%= @reservation.flight.departure_date.strftime("%d/%m/%Y") %></td>
					<td><%= @reservation.flight.departure_date.strftime("%H:%M") %></td>
				</tr>
			</tbody>
		</table>

		<h3>Travellers details</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Email</th>
					<th>Address</th>
				</tr>
			</thead>

			<tbody>
				<% @reservation.customers.each do |c| %>
					<tr>
						<td><%= c.name %></td>
						<td><%= c.email %></td>
						<td><%= c.address %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>



<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>