AdvancedReservationSystem/config/routes.rb
Rails.application.routes.draw do
  resources :extra_reservations
  resources :events
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :customer_reservations
  resources :customers
  resources :reservations
  resources :flights
  resources :airlines
  resources :airports
  resources :reservation_steps
  scope "extra_reservations/:extra_reservation_id" do
    resources :extra_steps
  end
  
  
  match "extra_steps/taxi", to: "extra_steps#taxi", via: "post"
  
  
  get 'admin' =>'admin'

  

  root 'flights#index'

end

AdvancedReservationSystem/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

AdvancedReservationSystem/app/models/airline.rb
class Airline < ActiveRecord::Base  
  
	has_many :airports, class_name: "Flight", foreign_key: "airport_id"
  
  validates :name, presence: true	
	validates :iata, presence: true
	validates :icao, presence: true
  validates :callsign, presence: true
  validates :headquarters, presence: true
end

AdvancedReservationSystem/app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
	has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
	has_many :extra_reservations, class_name: "ExtraReservation"

  validates :name, presence: true	
	validates :code, presence: true
	validates :city, presence: true
  validates :country, presence: true
end

AdvancedReservationSystem/app/models/attraction.rb
class Attraction < ActiveRecord::Base
  
	has_many :extra_reservations, class_name: "ExtraReservation"
  
end

AdvancedReservationSystem/app/models/customer.rb
class Customer < ActiveRecord::Base 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :address, presence: true
	
	has_many :reservations, through: :customer_reservations
	has_many :customer_reservations
	has_many :flights, through: :reservations	
end

AdvancedReservationSystem/app/models/customer_reservation.rb
class CustomerReservation < ActiveRecord::Base
	belongs_to :customer
	belongs_to :reservation
  
	validates :reservation_id, presence: true
	validates :customer_id, presence: true  
end

AdvancedReservationSystem/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :arrival_airport, class_name: "Airport"
 
  validates_presence_of :name, :description, :eventdate, :arrival_airport_id
    
  #Validte Date - must not be in the past
  validate :eventdate_cannot_be_in_the_past
  def eventdate_cannot_be_in_the_past
    if eventdate.present? && eventdate < Date.today
      errors.add(:eventdate, "Event can't be in the past, please check the date")
    end
  end
end

AdvancedReservationSystem/app/models/extra_reservation.rb
class ExtraReservation < ActiveRecord::Base
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :hotel_list, class_name: "HotelList"
  belongs_to :tour, class_name: "Tour"
  belongs_to :attraction, class_name: "Attraction"
  belongs_to :restaurant, class_name: "Restaurant"    
  belongs_to :user
        
end

AdvancedReservationSystem/app/models/flight.rb
class Flight < ActiveRecord::Base 
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :airline, class_name: "Airline"
  has_many :reservations
  # has_many :customers, through: :customer_reservations
  has_many :customers
  has_many :customer_reservations
  

  validates :departure_airport_id, presence: true
  validates :arrival_airport_id, presence: true
  validates :airline_id, presence: true
  validates :duration, presence: true
  validates :departure_date, presence: true
  validates :price, presence: true
  validates :availability, presence: true

  def self.date_list
    dates = Flight.all.order(departure_date: :asc)
    dates.map {|n| n.departure_date.strftime("%d/%m/%Y") }.uniq
  end

  def self.search(depart, arrive, airline, date)
    Flight.where(departure_airport_id: depart, 
    arrival_airport_id: arrive,
    airline_id: airline,
    departure_date: Flight.correct_date(date))
  end

  def self.correct_date(date)
    unless date.nil?
      date = date.to_date
      date.beginning_of_day..date.end_of_day
    end
  end	
end

AdvancedReservationSystem/app/models/hotel_list.rb
class HotelList < ActiveRecord::Base
  
	has_many :extra_reservations, class_name: "ExtraReservation"

end

AdvancedReservationSystem/app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :flight
  belongs_to :user
	has_many :customer_reservations
	has_many :customers, through: :customer_reservations

	validates :flight_id, presence: true

	accepts_nested_attributes_for :customers
  
end

AdvancedReservationSystem/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
	has_many :extra_reservations, class_name: "ExtraReservation"
  
end

AdvancedReservationSystem/app/models/tour.rb
class Tour < ActiveRecord::Base
  
	has_many :extra_reservations, class_name: "ExtraReservation"
  
end

AdvancedReservationSystem/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  
  has_many :reservations
  has_many :extra_reservations

  # enum role: [:user, :admin]
  # after_initialize :set_default_role, :if => :new_record?
  #
  # def set_default_role
  #   self.role ||= :user
  # end
        
end

AdvancedReservationSystem/app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_filter :authenticate_admin_user!, :only=> [:edit, :new, :destroy]

	def index
		@events=Event.all.where('eventdate>? OR eventdate==?',Date.today, Date.today).order(:eventdate)
	end

  private

    def event_params
      params.require(:event).permit(:name, :eventdate, :arrival_airport_id, :description, :price)
    end
end

AdvancedReservationSystem/app/helpers/application_helper.rb
module ApplicationHelper
end

AdvancedReservationSystem/app/helpers/events_helper.rb
module EventsHelper
end

AdvancedReservationSystem/app/helpers/extra_steps_helper.rb
module ExtraStepsHelper
end

AdvancedReservationSystem/app/helpers/flights_helper.rb
module FlightsHelper
end

AdvancedReservationSystem/app/helpers/reservations_helper.rb
module ReservationsHelper
end

AdvancedReservationSystem/app/views/layouts/_footer.html.erb
<footer>&copy; <%= Time.now.year %> University of Surrey &amp; Akinniyi A</footer>

AdvancedReservationSystem/app/views/layouts/_header.html.erb
<header>
	<p class="logo">
		<%= image_tag "ars_logo.png" %>
		 </p>

	<h2>Advanced Reservation System on Rails</h2>
</header>

AdvancedReservationSystem/app/views/layouts/_navbar.html.erb
<nav>
	<ul>
		<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
		<li class="<%= 'active' if current_page?(flights_path)%>"><%= link_to "New Flight", flights_path %></li>
		<li class="<%= 'active' if current_page?(reservations_path)%>"><%= link_to "Fight Reservations", reservations_path %></li>
		<li class="<%= 'active' if current_page?(extra_reservations_path)%>"><%= link_to "Extra Reservations", extra_reservations_path %></li>
		<li class="<%= 'active' if current_page?(events_path)%>"><%= link_to "Events", events_path %></li>
	</ul>
</nav>

AdvancedReservationSystem/app/views/layouts/_topbar.html.erb
<topbar>
    <p class="notice-right">
		<%= link_to 'Admin', admin_path %>
    	<% if user_signed_in? %>
    	Logged in as <strong><%= current_user.email %></strong>.
    	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    	<% else %>
    	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    	<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    	<% end %>
    </p>
</topbar>

AdvancedReservationSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Advanced Reservation System | <%=yield(:title)%></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'layouts/topbar' %>
	<%= render 'layouts/header' %>
	<navbar class="navclass">
		<%= render 'layouts/navbar' %>
	</navbar>
	
	<section class="container-fluid">
		<% flash.each do |message_type, message| %>
		<section class="alert alert-<%= message_type%> alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<ul><li><%= message %> </li> </ul>
		</section>
		<% end %>	
		<!-- <p class="alert"><%= alert %></p>	 -->
	</section>

	<section id="main">	
		<%= yield %>
	</section>
	
	<%= render 'layouts/footer' %>

</body>
</html>