AdvancedReservationSystem/config/routes.rb
Rails.application.routes.draw do
  resources :extra_reservations
  resources :events
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :customer_reservations
  resources :customers
  resources :reservations
  resources :flights
  resources :airlines
  resources :airports
  resources :reservation_steps
  scope "extra_reservations/:extra_reservation_id" do
    resources :extra_steps
  end
  
  
  match "extra_steps/taxi", to: "extra_steps#taxi", via: "post"
  
  
  get 'admin' =>'admin'

  

  root 'flights#index'

end

AdvancedReservationSystem/app/models/flight.rb
class Flight < ActiveRecord::Base 
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :airline, class_name: "Airline"
  has_many :reservations
  # has_many :customers, through: :customer_reservations
  has_many :customers
  has_many :customer_reservations
  

  validates :departure_airport_id, presence: true
  validates :arrival_airport_id, presence: true
  validates :airline_id, presence: true
  validates :duration, presence: true
  validates :departure_date, presence: true
  validates :price, presence: true
  validates :availability, presence: true

  def self.date_list
    dates = Flight.all.order(departure_date: :asc)
    dates.map {|n| n.departure_date.strftime("%d/%m/%Y") }.uniq
  end

  def self.search(depart, arrive, airline, date)
    Flight.where(departure_airport_id: depart, 
    arrival_airport_id: arrive,
    airline_id: airline,
    departure_date: Flight.correct_date(date))
  end

  def self.correct_date(date)
    unless date.nil?
      date = date.to_date
      date.beginning_of_day..date.end_of_day
    end
  end	
end

AdvancedReservationSystem/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!, :except => [:index]

  # GET /flights
  # GET /flights.json
  def index
    #@flights = Flight.all
    @airports = Airport.all.map do |a| 
      [a.name, a.id]
    end
    @airlines = Airline.all.map do |al| 
      [al.name, al.id]
    end
    @dates = Flight.date_list
    @customer_options = [1,2,3,4,5,6,7,8,9]
    @departure_airport = params[:departure_airport_id]
    @destination_airport = params[:arrival_airport_id]
    @depart_date = params[:departure_date]
    @customers = params[:customers]
    #@airlines = params [:airline_id]

    @flights = Flight.search(params[:departure_airport_id],
    params[:arrival_airport_id],
    params[:airline_id],
    params[:departure_date])	 	
    if params[:commit] == "Search"
      if params[:departure_airport_id] == params[:arrival_airport_id]
        flash[:danger] = "Your Departure Airport and Arrival Airport Should not be the Same"	
      end
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  # def show
  # end
  #
  # # GET /flights/new
  # def new
  #   @flight = Flight.new
  # end
  #
  # # GET /flights/1/edit
  # def edit
  # end
  #
  # # POST /flights
  # # POST /flights.json
  # def create
  #   @flight = Flight.new(flight_params)
  #
  #   respond_to do |format|
  #     if @flight.save
  #       format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
  #       format.json { render :show, status: :created, location: @flight }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @flight.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /flights/1
  # # PATCH/PUT /flights/1.json
  # def update
  #   respond_to do |format|
  #     if @flight.update(flight_params)
  #       format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @flight }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @flight.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /flights/1
  # # DELETE /flights/1.json
  # def destroy
  #   @flight.destroy
  #   respond_to do |format|
  #     format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_flight
  #     @flight = Flight.find(params[:id])
  #   end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def flight_params
  #     params.require(:flight).permit(:airline_id, :departure_airport_id, :arrival_airport_id, :departure_date, :duration, :price, :availability)
  #   end
end

AdvancedReservationSystem/app/helpers/flights_helper.rb
module FlightsHelper
end

AdvancedReservationSystem/app/views/flights/_newform.html.erb
<div class="row search">
	<div class="col-md-8 col-md-offset-2 well form-inline">

		<%= form_for(@flight) do |f| %>
		<% if @flight.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

			<ul>
				<% @flight.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="form-group">
			<%= f.label :airline_id %><br>
			<%= f.collection_select :airline_id, Airline.order(:name), :id, :name, :include_blank => "Select Airline"%>
		</div>
		<div class="form-group">
			<%= f.label :departure_airport_id %><br>
			<%= f.collection_select :departure_airport_id, Airport.order(:name), :id, :name, :include_blank => "Select Departure Airport"%>
		</div>
		<div class="form-group">
			<%= f.label :arrival_airport_id %><br>
			<%= f.collection_select :arrival_airport_id, Airport.order(:name), :id, :name, :include_blank => "Select Arrival Airport"%>
		</div>
		<div class="form-group">
			<%= f.label :departure_date %><br>
			<%= f.datetime_select :departure_date %>
		</div>
		<div class="form-group">
			<%= f.label :duration %><br>
			<%= f.number_field :duration %>
		</div>
		<div class="form-group">
			<%= f.label :price %><br>
			<%= f.number_field :price %>
		</div>
		<div class="form-group">
			<%= f.label :availability %><br>
			<%= f.select :availability, ['Available', 'Full'] %>
		</div>
		<br>
		<div>
			<%= f.submit %>
		</div>
		<% end %>

		<br>
		<%= link_to 'Back', flights_path %>

	</div>

</div>

AdvancedReservationSystem/app/views/flights/_searchform.html.erb
<div class="row search">

	<div class="col-sm-6 col-sm-offset-3 well">
		<h3>Search for flight</h3>

		<%= form_tag(flights_path, method: "get") do %>

		<div class="form-group col-md-6 rm-p">
			<%= label_tag(:departure_airport_id, "Departure Airport:") %>
			<%= select_tag(:departure_airport_id, options_for_select(@airports, @departure_airport), class: "form-control") %>
		</div>

		<div class="form-group col-md-6">
			<%= label_tag(:arrival_airport_id, "Arrival Airport:") %>
			<%= select_tag(:arrival_airport_id, options_for_select(@airports, @arrival_airport), class: "form-control", id: "arrival-select") %>
		</div>

		<div class="form-group col-md-6 rm-p">
			<%= label_tag(:departure_date, "Date:") %>
			<%= select_tag(:departure_date, options_for_select(@dates, @depart_date), class: "form-control") %>
		</div>

		<div class="form-group col-md-6" >
			<%= label_tag(:customers, "Number of Travellers:") %>
			<%= select_tag(:customers, options_for_select(@customer_options, @customers), class: "form-control") %>
		</div>
		
		<div class="form-group col-md-6 rm-p">
			<%= label_tag(:airline_id, "Preferred Airline:") %>
			<%= select_tag(:airline_id, options_for_select(@airlines, @airlines), class: "form-control", :include_blank => "Select Preferred Airline") %>
		</div>

		<%= submit_tag "Search", class: "btn btn-success col-md-3 col-md-offset-5" %>
		<% end %>
	</div>
</div>


<% unless @flights.empty? %>
<div class="row search-results">
<h1>Flight Search Result</h1>
	<div class="col-md-10 col-md-offset-1 well">
		<h3>Choose a flight</h3>

		<table class="table table-hover">
			<thead>
				<tr>
					<th></th>
					<th>Flight No:</th>
					<th>Airline</th>
					<th>Departure City</th>
					<th>Arrival City</th>
					<th>Departure Date</th>
					<th>Departure Time</th>
					<th>Duration</th>
					<th>Price</th>
					<th>Availability</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<%= form_tag(new_reservation_path, method: "get") do %>
			<tbody>
				<% @flights.each do |flight| %>
				<tr>
					<td><%= radio_button_tag(:flight_id, flight.id,class: "flight_select")  %></td>
					<td><%= flight.id %></td>
					<td><%= flight.airline.name %></td>
					<td><%= flight.departure_airport.city %></td>
					<td><%= flight.arrival_airport.city %></td>
					<td><%= flight.departure_date.strftime("%d/%m/%Y") %></td>
					<td><%= flight.departure_date.strftime("%H:%M") %></td>
					<td><%= flight.duration %></td>
					<td><%= flight.price %></td>
					<td><%= flight.availability %></td>
					<td><%= link_to 'Show', flight %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		
		<%= hidden_field_tag(:customers, params[:customers]) %>
		<%= submit_tag"Continue", class: "btn btn-success col-md-3 col-md-offset-5" %>
		<% end %>

	</div>
	
	<br>
	
</div>
<% end %>

AdvancedReservationSystem/app/views/flights/index.html.erb
<%= render 'searchform' %>

AdvancedReservationSystem/app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'newform' %>